### ISSUE TITLE
Order-dependent failure: test_skill_index_prompt_injection leaks a stub routes.prefs_routes into sys.modules

### ISSUE THREAD

**Issue by victorv2i** [pewdiepie-archdaemon/odysseus#4386]
## Prerequisites

- [x] I searched open issues and discussions and did not find an existing report of this bug.
- [x] This is not a security vulnerability.
- [x] I am running the latest `dev` branch and the bug still reproduces there.

## Install Method

Manual Python install (pip / venv)

## Operating System

Linux

## Steps to Reproduce

This is a test-isolation problem: the failing test passes on its own and only fails when `tests/test_skill_index_prompt_injection.py` is collected before it.

1. `python -m venv .venv && . .venv/bin/activate && pip install -r requirements.txt`
2. Run the two files together so the skill-index file is collected first:
   `python -m pytest tests/test_skill_index_prompt_injection.py tests/test_backup_import_skills.py`
3. It also reproduces in the full suite under a shuffled order, e.g. `python tests/run_order_report.py --seed 1826097079`.

## Expected Behaviour

`tests/test_backup_import_skills.py` passes regardless of what runs before it (it passes when run on its own).

## Actual Behaviour

After `test_skill_index_prompt_injection` runs, `test_import_adds_new_skill_via_add_skill` fails with:

```
ImportError: cannot import name '_save_for_user' from 'routes.prefs_routes' (unknown location)
```

Cause: `_patch_prefs` in `tests/test_skill_index_prompt_injection.py` installs a fake `routes.prefs_routes` with a bare assignment that bypasses monkeypatch:

```python
fake_prefs = types.ModuleType("routes.prefs_routes")
fake_prefs._load_for_user = lambda user=None: {...}
sys.modules["routes.prefs_routes"] = fake_prefs   # never restored
```

The empty stub (no `_save_for_user`) stays in `sys.modules` after the test, so `routes/backup_routes.py`'s `from routes.prefs_routes import _save_for_user` fails on a later test. Every other `routes.prefs_routes` stub in the suite uses `monkeypatch.setitem`, which reverts; this one is the only bare assignment.

## Are you willing to submit a fix?

Yes. The one-line fix is to install the stub with `monkeypatch.setitem(...)` (the helper already takes `monkeypatch` and uses it for `DATA_DIR`) so it is reverted at teardown.
