### PR TITLE
fix(models): query v1 models for llama-server endpoints

### LINKED ISSUE #3330: Issue with the llama-server integration
### Prerequisites

- [x] I searched [open issues](https://github.com/pewdiepie-archdaemon/odysseus/issues?q=is%3Aissue+is%3Aopen) and [discussions](https://github.com/pewdiepie-archdaemon/odysseus/discussions) and did not find an existing report of this bug.
- [x] This is **not** a security vulnerability. (Vulnerabilities go to [GitHub Security Advisories](https://github.com/pewdiepie-archdaemon/odysseus/security/advisories/new) — see [SECURITY.md](https://github.com/pewdiepie-archdaemon/odysseus/blob/main/SECURITY.md).)
- [x] I am running the latest code from `main`.

### Install Method

Docker (docker compose up)

### Operating System

Linux

### Steps to Reproduce

1.Add llama-serve endpoint
2.Switch agent mode
3. Send some message

### Expected Behaviour

Processing request

### Actual Behaviour

Error "Enpoint offline canceling in 5s"

### Logs / Screenshots

```text
srv  log_server_r: done request: GET /v1 192.168.XX.XX 404
```

### Model / Backend (if relevant)

llama-server+ Qwen3.6-35B-A3B-GGUF:UD

### Are you willing to submit a fix?

No — I am only filing the report

### Additional Information

Hi! There's an issue with the llama-server integration. The core problem is that the URL is constructed incorrectly when checking endpoint availability. I've fixed it on my end.
 There were three places where an incorrect URL was being built for a GET request to http://host:port/v1 (without /models):
**routes/model_routes.py:757 — _ping_endpoint** (this is the main cause of the "Endpoint offline" issue). The endpoint availability check function was sending a GET request to <base>, where base could be http://192.168.XX.XX:8080/v1. It now uses build_models_url(base) → GET /v1/models.

**src/model_context.py:302-307 — _query_context_length**. When querying the model context, it was doing endpoint_url.replace("/chat/completions", "/models"), which was a no-op for URLs without /chat/completions. It now handles /v1 → appends /models.

**src/llm_core.py:940-945 — list_model_ids**. Same pattern, same fix.

### PR DESCRIPTION
**Pull request by undergroundrap**
## Summary

Fixes llama-server/OpenAI-compatible endpoints configured directly as `/v1` by routing model-list probes through the shared `build_models_url()` helper instead of deriving `/models` with ad hoc string replacement.

Before this, `src/model_context.py` and `src/llm_core.py` only replaced `/chat/completions` with `/models`, so a base like `http://host:8080/v1` could be queried as `GET /v1` instead of `GET /v1/models`. `_ping_endpoint` now also uses the same helper for its 404 fallback path, keeping the route probe aligned with the shared endpoint resolver.

The shared `build_models_url()` helper now normalizes already-expanded URLs first, so both `http://host:8080/v1` and `http://host:8080/v1/chat/completions` resolve to `http://host:8080/v1/models`.

Duplicate check: I checked #3330 and searched open PRs for the issue number and same llama-server/model-list URL area. I did not find an active PR fixing this `/v1` model-list derivation path.

## Target branch

- [x] This PR targets **`dev`**, not `main`.

## Linked Issue

Fixes #3330

## Type of Change

- [x] Bug fix (non-breaking - fixes a confirmed issue)
- [ ] New feature (non-breaking - adds new behaviour)
- [ ] Breaking change (changes or removes existing behaviour)
- [ ] Refactor / cleanup (behaviour unchanged)
- [ ] Documentation only
- [ ] CI / tooling / configuration

## Checklist

- [x] I searched [open issues](https://github.com/pewdiepie-archdaemon/odysseus/issues) and [open PRs](https://github.com/pewdiepie-archdaemon/odysseus/pulls) - this is not a duplicate.
- [x] This PR targets `dev`
- [x] My changes are limited to the scope described above - no unrelated refactors or whitespace changes mixed in.
- [ ] I actually ran the app (`docker compose up` or `uvicorn app:app`) and verified the change works end-to-end. Type-checks and unit tests are not enough.

Backend/provider-path note: I did not claim a manual llama-server run. I verified the affected model-list and context-probe paths with Docker-based mocked HTTP regression tests, without requiring a real llama-server instance.

A real llama-server manual run would still be useful confirmation from someone with that setup, but the regression test pins the URL construction bug reported in #3330.

## How to Test

From the repository root, run the focused Docker regression set:

    docker compose run --rm --no-deps --entrypoint python -e PYTHONDONTWRITEBYTECODE=1 --volume "${PWD}:/app" odysseus -m pytest -q -p no:cacheprovider tests/test_llama_server_models_url.py tests/test_endpoint_resolver.py tests/test_provider_endpoints.py tests/test_model_context.py tests/test_model_routes.py

Expected result: `233 passed`.

Optional syntax check:

    docker compose run --rm --no-deps --entrypoint python -e PYTHONDONTWRITEBYTECODE=1 --volume "${PWD}:/app" odysseus -m py_compile src/endpoint_resolver.py src/model_context.py src/llm_core.py routes/model_routes.py tests/test_llama_server_models_url.py

The new regression coverage verifies:

- `build_models_url("http://127.0.0.1:8080/v1")` returns `/v1/models`.
- `build_models_url("http://127.0.0.1:8080/v1/chat/completions")` also returns `/v1/models`.
- `llm_core.list_model_ids()` queries `/v1/models` for a llama-server-style `/v1` endpoint.
- `model_context._query_context_length()` queries `/v1/models` after the local `/slots` probe does not return context metadata.

## Visual / UI changes - REQUIRED if you touched anything that renders

N/A - backend/provider URL handling and tests only. No UI rendering, CSS, HTML, SVG, or `static/js` files touched.

### Screenshots / clips

N/A - no visual/UI change. Verification is the Docker regression set listed above.

### CODE REVIEW

**Review by vdmkenny — APPROVED** [review]
LGTM, thanks. Routing the model-list derivation through `build_models_url()` (with `normalize_base`) is the right DRY fix, and the `/v1` bare-base case now resolves to `/v1/models` while `/chat/completions` bases still do. Verified no regression across openai/anthropic/groq/ollama/google; 118 tests pass in the focused set.

**Review by vdmkenny — CHANGES_REQUESTED** [review]
Retracting my approval: CI "Python tests (pytest)" is red, and it is this PR's own new test.

`tests/test_llama_server_models_url.py::test_llm_core_list_model_ids_queries_models_for_v1_base` fails in the full suite:

```
TypeError: <lambda>() got an unexpected keyword argument 'owner'
```

`list_model_ids` calls `_configured_cached_model_ids(base_chat_url, owner=owner, endpoint_id=endpoint_id)`, but the test mocks it with `lambda url: []`, which rejects the kwargs. Dev gained owner-scoping on that call after this branch was written, so the mock is now stale. (It passes in isolation only because of ordering.)

Fix: make the mock accept the kwargs, e.g. `lambda url, **kwargs: []` (or `lambda url, owner=None, endpoint_id=None: []`), and rebase onto current `dev`. The actual `build_models_url` change looks good; just the test needs to match the current signature.

**Comment by undergroundrap** [comment]
@vdmkenny 

Thanks, you were right. I rebased this branch onto current `dev` and fixed the stale test mock to accept the new owner-scoped kwargs. 

The production `build_models_url()` path remains unchanged. This follow-up simply updates the regression mock from `lambda url: []` to `lambda url, **kwargs: []` so it matches the current `_configured_cached_model_ids(base_chat_url, owner=..., endpoint_id=...)` call signature.

Verified locally after the rebase:
* `tests/test_llama_server_models_url.py`: `3 passed, 1 warning`
* Focused test set (`test_llama_server_models_url.py`, `test_endpoint_resolver.py`, etc.): `222 passed, 1 warning`
* `py_compile` on changed Python files: Clean!

**Review by vdmkenny — APPROVED** [review]
LGTM, thanks. The `_configured_cached_model_ids` mock now accepts the `owner`/`endpoint_id` kwargs, so the regression test passes in-suite again. The core fix (routing model-list derivation through `build_models_url` so a bare `/v1` base resolves to `/v1/models`) is solid. Verified: full suite green (2826 passed), no provider regressed.
